### ISSUE TITLE
Nine Manga support

### ISSUE THREAD

**Issue by adbenitez** [driverog/tg-manga-bot#10]
hi, if you are interested in adding support for Nine Manga site, check:
https://github.com/adbenitez/simplebot_manga/blob/master/simplebot_manga/manga_api/ninemanga.py

it should be easy for you to adapt to your code (or take the scrapping steps), it has similar structure to your plugins

**Comment by driverog** [comment]
Thanks, closing this issue because NineManga was added to the bot.
