### ISSUE TITLE
It closes time to time

### ISSUE THREAD

**Issue by titu3e** [driverog/tg-manga-bot#5]
It closes time to time with socket error

**Comment by driverog** [comment]
I haven't been able to reproduce this error. Does it happen when client losses internet connection ?

**Comment by NatuRao** [comment]
@driverog Guys how do you save the chapter images in mangakakalot.com? It shows me Access Denied every time I try to `requets.get(<image_src>)`
Can you guys help me with it? I am looking for this since January.

Here is the image of the Access Denied error I am getting: https://ibb.co/syt1SLT

**Comment by driverog** [comment]
You need to set 'Referer' header. You can check the function [get_picture](https://github.com/driverog/tg-manga-bot/blob/b4b223a10ddc77ba9976cedbb0663b807bc8b219/plugins/mangakakalot.py#L91). Please, next time create a new issue.

**Comment by NatuRao** [comment]
@driverog Thank you so so much, I was looking for this from a long time. It was very helpful!

I didn't think think of an issue, I only wanted to ask question, that's why I didn't create new issue.

But Thank you so much, you were a big help!
